local modname = ...
local sources = {
	{
		type = 'native',
		name = 'client-console/main',
		noheader = true,
		use = 'console',
	},
	{
		type = 'native',
		name = 'client-main/main',
		noheader = true,
		use = 'main',
	},
	{
		type = 'native',
		name = 'common',
		headeronly = true,
		use = 'console;main',
	},
	{
		type = 'native',
		name = 'osapi',
		headeronly = true,
		use = 'console;main',
	},
	{
		type = 'native',
		name = 'utils/cbase',
		use = 'console;main',
		methodlist = true,
	},
	{
		type = 'native',
		name = 'utils/configset',
		use = 'console;main',
		methodlist = true,
	},
	{
		type = 'native',
		name = 'utils/console',
		use = 'console;main',
	},
	{
		type = 'native',
		name = 'utils/cyclicbuffer',
		use = 'console;main',
	},
	{
		type = 'native',
		name = 'utils/databuffer',
		headeronly = true,
		use = 'console;main',
		methodlist = true,
	},
	{
		type = 'native',
		name = 'utils/encoding',
		use = 'console;main',
		methodlist = true,
	},
	{
		type = 'native',
		name = 'utils/flaglock',
		headeronly = true,
		use = 'console;main',
	},
	{
		type = 'native',
		name = 'utils/mpsclist',
		headeronly = true,
		use = 'console;main',
	},
	{
		type = 'native',
		name = 'utils/mpscqueue',
		headeronly = true,
		use = 'console;main',
	},
	{
		type = 'native',
		name = 'utils/path',
		use = 'console;main',
	},
	{
		type = 'native',
		name = 'utils/profile',
		headeronly = true,
		use = 'console;main',
	},
	{
		type = 'native',
		name = 'utils/ref',
		headeronly = true,
		use = 'console;main',
	},
	{
		type = 'native',
		name = 'utils/refobject',
		headeronly = true,
		use = 'console;main',
		methodlist = true,
	},
	{
		type = 'native',
		name = 'utils/singleton',
		headeronly = true,
		use = 'console;main',
	},
	{
		type = 'native',
		name = 'utils/strexception',
		headeronly = true,
		use = 'console;main',
	},
	{
		type = 'native',
		name = 'utils/string',
		headeronly = true,
		use = 'console;main',
	},
	{
		type = 'native',
		name = 'rsbin/common',
		use = 'console;main',
		methodlist = true,
	},
	{
		type = 'native',
		name = 'rsbin/fileio',
		use = 'console;main',
		methodlist = true,
	},
	{
		type = 'native',
		name = 'rsbin/fsthread',
		use = 'console;main',
		methodlist = true,
	},
	{
		type = 'native',
		name = 'rsbin/pngcommon',
		headeronly = true,
		use = 'console;main',
		methodlist = true,
	},
	{
		type = 'native',
		name = 'rsbin/pngreader',
		use = 'console;main',
		methodlist = true,
	},
	{
		type = 'native',
		name = 'rsbin/pngwriter',
		use = 'console;main',
		methodlist = true,
	},
	{
		type = 'native',
		name = 'client-console/window',
		use = 'console',
		methodlist = true,
	},
	{
		type = 'native',
		name = 'graphics/clearshape',
		use = 'main',
		methodlist = true,
	},
	{
		type = 'native',
		name = 'graphics/common',
		use = 'main',
	},
	{
		type = 'native',
		name = 'graphics/context',
		use = 'main',
	},
	{
		type = 'native',
		name = 'graphics/display',
		use = 'main',
	},
	{
		type = 'native',
		name = 'graphics/primitiveshape',
		use = 'main',
		methodlist = true,
	},
	{
		type = 'native',
		name = 'graphics/programtranslator',
		use = 'console',
		methodlist = true,
	},
	{
		type = 'native',
		name = 'graphics/programtranslator-base',
		use = 'console',
		headeronly = true,
	},
	{
		type = 'native',
		name = 'graphics/programtranslator-functions',
		use = 'console',
		headeronly = true,
	},
	{
		type = 'native',
		name = 'graphics/programtranslator-generators',
		use = 'console',
		headeronly = true,
	},
	{
		type = 'native',
		name = 'graphics/programtranslator-state',
		use = 'console',
		headeronly = true,
	},
	{
		type = 'native',
		name = 'graphics/programtranslator-step',
		use = 'console',
		headeronly = true,
	},
	{
		type = 'native',
		name = 'graphics/resource',
		use = 'main',
		methodlist = true,
	},
	{
		type = 'native',
		name = 'graphics/shape',
		use = 'main',
		methodlist = true,
	},
	{
		type = 'native',
		name = 'graphics/shapegroup',
		use = 'main',
		methodlist = true,
	},
	{
		type = 'native',
		name = 'graphics/staticvertexbuffer',
		use = 'main',
		methodlist = true,
	},
	{
		type = 'native',
		name = 'graphics/vertexbuffer',
		use = 'main',
		methodlist = true,
	},
	{
		type = 'native',
		name = 'graphics/vertexdeclaration',
		use = 'main',
		methodlist = true,
	},
	{
		type = 'native',
		name = 'client-main/event',
		headeronly = true,
		use = 'main',
		methodlist = true,
	},
	{
		type = 'native',
		name = 'client-main/window',
		use = 'main',
		methodlist = true,
	},
	{
		type = 'luainit',
		name = 'luainit/main',
	},
	{
		type = 'luainit',
		name = 'luainit/baselib',
	},
	{
		type = 'luainit',
		name = 'luainit/object',
	},
	{
		type = 'luainit',
		name = 'luainit/ffipure',
	},
	{
		type = 'luainit',
		name = 'luainit/hostlib',
	},
}

package.modtable(modname, sources)
